- name: Add OpenJDK PPA
  become: true
  environment: "{{proxy_env}}"
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
- name: Perform system upgrade
  become: true
  environment: "{{proxy_env}}"
  apt:
    upgrade: yes
    update_cache: yes
- name: Install Java
  become: true
  environment: "{{proxy_env}}"
  apt:
    name: openjdk-8-jdk
- name: Download Hadoop
  become: yes
  environment: "{{proxy_env}}"
  unarchive:
    src: https://archive.apache.org/dist/hadoop/common/hadoop-2.7.3/hadoop-2.7.3.tar.gz
    dest: /home/hadoop
    remote_src: yes
    owner: hadoop
    group: hadoop
- name: Upload hadoop config
  become: yes
  copy:
    src: "{{ item }}"
    dest: /home/hadoop/hadoop-2.7.3/etc/hadoop/
    owner: hadoop
    group: hadoop
  with_fileglob:
    - "files/csci4180_hadoop_conf/*"
- name: Export JAVA_HOME
  become: yes
  lineinfile:
    dest: /home/hadoop/.bashrc
    regexp: "export JAVA_HOME="
    line: "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
- name: Export HADOOP_HOME
  become: yes
  lineinfile:
    dest: /home/hadoop/.bashrc
    regexp: "export HADOOP_HOME="
    line: "export HADOOP_HOME=/home/hadoop/hadoop-2.7.3"
- name: Export HADOOP_CLASSPATH
  become: yes
  lineinfile:
    dest: /home/hadoop/.bashrc
    regexp: "export HADOOP_CLASSPATH="
    line: "export HADOOP_CLASSPATH=${JAVA_HOME}/lib/tools.jar"
- name: Export PATH
  become: yes
  lineinfile:
    dest: /home/hadoop/.bashrc
    regexp: "export PATH="
    line: "export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin"
