- name: Set VM hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
- name: Build /etc/hosts file
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
  with_items: "{{ groups['all'] }}"
- name: Create hadoop user
  become: true
  user:
    name: hadoop
    shell: /bin/bash
    generate_ssh_key: yes
- name: Install hadoop user private key
  become: true
  copy:
    src: "../keys/{{ inventory_hostname }}-hadoop"
    dest: /home/hadoop/.ssh/id_rsa
    mode: 0600
    owner: hadoop
- name: Install hadoop user public key
  become: true
  copy:
    src: "../keys/{{ inventory_hostname }}-hadoop.pub"
    dest: /home/hadoop/.ssh/id_rsa.pub
    owner: hadoop
- name: Add public keys to authorized_keys
  become: true
  authorized_key:
    user: hadoop
    state: present
    key: "{{ lookup('file', '../keys/'+item+'-hadoop.pub') }}"
  with_items: "{{ groups['all'] }}"
- name: Disable host key checking
  become: true
  copy:
    src: "files/hadoop-ssh-config"
    dest: /home/hadoop/.ssh/config
    owner: hadoop


